theme: jekyll-theme-minimal
title: Munich Computer Systems Research Lab
description: """
## Opportunities
If getting a PhD sounds interesting, and some of the topics below sound interesting, too, then please get in touch with us! Email address is u c s r l at unibw dot de

### No Army Affiliation needed!
Because students keep asking us:
Our PhD researchers are **not** in any way affiliated with Germany's armed forces but normal, civilian PhD students that have obtained their Master's degrees from other universities (TU Munich, TU Wien, and HHU, to be precise).
Although most of our Bachelor and Masters students are, in fact, officers in the German Bundeswehr, most of them continue in their military career.

If you have an accredited Master's degree from a European university, you are welcome to join Î¼CSRL! (And you will also not have to perform any military duties.)
"""
logo: ucsrl.png
url: "https://ucsrl.de"

github:
  is_project_page: false
  is_user_page: false

plugins:
  - jekyll-sitemap
